### ISSUE TITLE
cmake_compile_definitions doesn't work

### ISSUE THREAD

**Issue by KingDuckZ** [dcarp/cmake-d#19]
I have a mixed C and D project. In my cmake file I have:

    target_compile_definitions(${PROJECT_NAME}
        PRIVATE MG_ENABLE_HTTP_URL_REWRITES
    )

When I compile with make VERBOSE=1 I see the -D flag passed for the .c files but not for the .d files. I'm using the gdc compiler.

**Comment by dcarp** [comment]
D does not have a preprocessor so that `target_compile_definitions` has no effect for the .d files.
Alternatively you could use [version](https://dlang.org/spec/version.html#version-specification):
```CMake
target_compile_options(${PROJECT_NAME}
    PRIVATE -version=MG_ENABLE_HTTP_URL_REWRITES
)
```
Applying this just for the .d files can be done using some [cmake generator](https://cmake.org/cmake/help/v3.0/manual/cmake-generator-expressions.7.html) magic.

**Comment by KingDuckZ** [comment]
Thanks, I had no idea I could pass entire options to target_compile_definitions. I thought I was restricted to valid C tokens.
